// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtbftxitlgqwlaxcydts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0YmZ0eGl0bGdxd2xheGN5ZHRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MzE3MzgsImV4cCI6MjA2NzQwNzczOH0.NR4XSTU_-DNcWAZ1cL6fSt_0EmWhbW6-fU2nYP6-UFk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});